// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrdexjselrpcvdyxnbuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZGV4anNlbHJwY3ZkeXhuYnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3ODgzMTMsImV4cCI6MjA1NDM2NDMxM30.zhjDd-kVMrUIFPV3m69-UnUaYojOq4vmzQOC81DxdfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);