// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otevpwalhbogsiegvpnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90ZXZwd2FsaGJvZ3NpZWd2cG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MjQ2MjUsImV4cCI6MjA1NDQwMDYyNX0.xgmt1g0F3DYEiVa1N0gdbWw85eJWNIoUiXm2boKZhVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);